name: Design Tokens to Figma

on:
  pull_request_review:
    types: [submitted]
    branches:
      - main
    paths:
      - "design-tokens/tokens/**"
      - ".github/workflows/sync-tokens-to-figma.yml"
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - "design-tokens/tokens/**"
      - ".github/workflows/sync-tokens-to-figma.yml"

jobs:
  sync-figma-variables:
    runs-on: ubuntu-latest
    if: (github.event.review.state == 'approved') || (github.event.pull_request.merged == true)
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://npm.pkg.github.com"
          scope: "@serendie"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_GITHUB_PACKAGES_TOKEN }}

      - name: Set NPM version
        run: npm install -g npm@latest

      - name: Clone repo
        uses: actions/checkout@v4

      - name: Cache Dependency
        uses: actions/cache@v4
        id: cache_dependency
        env:
          cache-name: cache-dependency
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: ${{ steps.cache_dependency.outputs.cache-hit != 'true' }}
        run: npm install

      - name: Sync json to Figma file
        run: npm run sync-to-figma --silent
        env:
          FILE_KEY: ${{ secrets.SYNC_FIGMA_FILE_KEY }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.SYNC_FIGMA_PERSONAL_ACCESS_TOKEN }}
